#pragma once
#define SUBMENU_BACGROUND_COLOR		0x333333
#define SUBMENU_ACTIVE_ITME_COLOR	0x0B72AB
#define SUBMENU_NORMAL_ITEM_COLOR	0x494949
#define SETTINGS_TEXTAREA_BORDER_COLOR	0x858585
typedef enum
{
	SETTINGS_SUBMENU_BLUETOOTH,
	SETTINGS_SUBMENU_WIFI,
	SETTINGS_SUBMENU_OPC,
	SETTINGS_SUBMENU_SERIAL,
	SETTINGS_SUBMENU_SDCARD,
}SETTINGS_SUBMENU_TYPE;

extern lv_obj_t* ui_settings_screen;
void ui_settings_screen_init();